apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 949092020730.dkr.ecr.us-east-1.amazonaws.com/project2-three-tier-pipeline/frontend:3
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://muralirajendran.click/api/tasks"
          ports:
            - containerPort: 3000
